package dev.learning.platform.collector;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.kafka.clients.consumer.ConsumerRecord;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.kafka.support.Acknowledgment;
import org.springframework.stereotype.Component;

@Component
public class SourceFileCdcListener {
    private static final Logger log = LoggerFactory.getLogger(SourceFileCdcListener.class);
    private final ObjectMapper objectMapper;
    private final EventDrivenCollector collector;
    private final KafkaTemplate<String, String> kafkaTemplate;

    public SourceFileCdcListener(ObjectMapper objectMapper, EventDrivenCollector collector,
                                 KafkaTemplate<String, String> kafkaTemplate) {
        this.objectMapper = objectMapper;
        this.collector = collector;
        this.kafkaTemplate = kafkaTemplate;
    }

    @KafkaListener(topics = "orders-cdc.public.source_files")
    public void consume(ConsumerRecord<String, String> record, Acknowledgment acknowledgment)
            throws Exception {
        JsonNode envelope = objectMapper.readTree(record.value());
        String operation = envelope.path("op").asText();
        JsonNode after = envelope.path("after");
        // Updates generated by PROCESSING/COMPLETED/INVALID status changes are CDC
        // events too. Only the original insert represents new work.
        if ("c".equals(operation) && "PENDING".equals(after.path("status").asText())) {
            SourceFileEvent event = SourceFileEvent.from(envelope);
            log.info("Received file={} batch={} partition={} offset={}", event.fileName(),
                    event.batchId(), record.partition(), record.offset());
            // Wait while work runs on the bounded worker pool. A crash before this
            // future completes leaves the Kafka record unacknowledged for redelivery.
            CollectorProcessingResult result = collector.accept(event).get();
            if (result.deadLetterRequired()) {
                kafkaTemplate.send("source-files.DLT", record.key(), record.value()).get();
                collector.deadLettered(event, result.error());
                log.error("Published file={} to source-files.DLT after retries", event.fileName());
            }
        }
        acknowledgment.acknowledge();
        log.info("Acknowledged source-file partition={} offset={}",
                record.partition(), record.offset());
    }
}
